[workspace]
resolver="2"

members = [
  "ndisprot-kmdf",
  "wdf-kmdf-sys",
  "windows-kernel-sys",
  "windows-kernel-rs",
  "wdf-kmdf",
  "vtable"
]

[workspace.dependencies]
vtable = {path = "vtable"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
