[package]
name = "ndisprot-kmdf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wdf-kmdf-sys = { path = "../wdf-kmdf-sys" }

[build-dependencies]
thiserror = "1.0.40"
winreg = "0.50.0"
